let jokes = [
  {
    category: "Misc",
    type: "single",
    joke: "Schrödinger's cat walks into a bar and doesn't.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 197,
    safe: true,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "I bought some shoes from a drug dealer. I don't know what he laced them with, but I was tripping all day!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 204,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'A man is smoking a cigarette and blowing smoke rings into the air. His girlfriend becomes irritated with the smoke and says "Can\'t you see the warning on the cigarette pack? Smoking is hazardous to your health!" to which the man replies, "I am a programmer.  We don\'t worry about warnings; we only worry about errors."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 38,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Being a self-taught developer is almost the same as being a cut neck chicken because you have no sense of direction in the beginning.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 184,
    safe: false,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: "I didn't vaccinate my 10 kids and the one that survived is fine!",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 96,
    safe: false,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: 'Two fish in a tank. One turns to the other and says, "Do you know how to drive this thing?"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 185,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "My husband and I were happy for 20 years. And then we met.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 273,
    lang: "en",
  },
  {
    category: "Pun",
    type: "single",
    joke: "How do you make holy water? You boil the hell out of it.",
    flags: {
      nsfw: false,
      religious: true,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 202,
    safe: false,
    lang: "en",
  },
  {
    category: "Dark",
    type: "single",
    joke: "Dark humor is like food, not everyone gets it.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: true,
      sexist: false,
      explicit: true,
    },
    id: 162,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Your momma is so fat, you need to switch to NTFS to store a picture of her.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 55,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'A guy walks into a bar and asks for 1.4 root beers.\nThe bartender says "I\'ll have to charge you extra, that\'s a root beer float".\nThe guy says "In that case, better make it a double."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 2,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: '"Honey, go to the store and buy some eggs."\n"OK."\n"Oh and while you\'re there, get some milk."\nHe never returned.',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 18,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "The six stages of debugging:\n1. That can't happen.\n2. That doesn't happen on my machine.\n3. That shouldn't happen.\n4. Why does that happen?\n5. Oh, I see.\n6. How did that ever work?",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 123,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "A programmer puts two glasses on his bedside table before going to sleep.\nA full one, in case he gets thirsty, and an empty one, in case he doesn't.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 3,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Programming is 10% science, 20% ingenuity, and 70% getting the ingenuity to work with the science.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 37,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: '"Knock, knock."\n"Who\'s there?"\n\n[very long pause]\n\n"Java."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 36,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: 'A man is smoking a cigarette and blowing smoke rings into the air. His girlfriend becomes irritated with the smoke and says "Can\'t you see the warning on the cigarette pack? Smoking is hazardous to your health!" to which the man replies, "I am a programmer.  We don\'t worry about warnings; we only worry about errors."',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 38,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "ASCII silly question, get a silly ANSI.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 25,
    safe: true,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "Your mama's so FAT she can't save files bigger than 4GB.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    id: 9,
    safe: false,
    lang: "en",
  },
  {
    category: "Programming",
    type: "single",
    joke: "The generation of random numbers is too important to be left to chance.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 39,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Relationship Status: just tried to reach for my dog's paw and he pulled it away so I pretended I was reaching for the remote.",
    flags: {
      nsfw: false,
      religious: false,
      racist: false,
      sexist: false,
      political: false,
      explicit: false,
    },
    id: 195,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: 'A neutron walks into a bar and asks for a price on a drink.\nThe barkeeper says: "For you... no charge!"',
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 73,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "What does the MacBook have in common with Donald Trump?\n\nI would tell you....\nBut I don't compare apples to oranges.",
    flags: {
      nsfw: false,
      religious: false,
      political: true,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 233,
    safe: false,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "My husband and I were happy for 20 years. And then we met.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 273,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "I visited my friend at his new house. He told me to make myself at home. So I threw him out. I hate having visitors.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 304,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Yo mama is so old, she knew Burger King while he was still a prince.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    safe: true,
    id: 306,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "If you're here for the yodeling lesson, please form an orderly orderly orderly queue.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: false,
    },
    id: 139,
    safe: true,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "I went to the zoo the other day. There was only a dog in it – it was a shihtzu.",
    flags: {
      nsfw: false,
      religious: false,
      political: false,
      racist: false,
      sexist: false,
      explicit: true,
    },
    safe: false,
    id: 307,
    lang: "en",
  },
  {
    category: "Misc",
    type: "single",
    joke: "Women are like KFC, once you're done with the breasts and thighs, you just have a greasy box to put your bone in.",
    flags: {
      nsfw: true,
      religious: false,
      political: false,
      racist: false,
      sexist: true,
      explicit: true,
    },
    id: 149,
    safe: false,
    lang: "en",
  },
];


function randomJoke(){
  let data = Math.floor(Math.random() * jokes.length - 1);

let joke = document.getElementById("joke");
joke.innerHTML = jokes[data].joke;
}

randomJoke();